var XGManageDes =  
{  
	s0100:    "Esta página permite consultar información sobre la tarjeta de datos en uso, especificar una red y configurar el número de PIN para la tarjeta SIM.",				
	s2101:    "Configuración de conexión de red",
	s2102:    "Se puede consultar la información de la versión de la tarjeta de datos y consultar o especificar la red a la que se está conectado a través de la tarjeta SIM.",
	s2103:    "Nombre de la tarjeta de datos:",
	s2104:    "Versión de software de la tarjeta de datos:",
	s2105:    "Versión de hardware de la tarjeta de datos:",
	s2106:    "Red actual a la que está conectado:",
	s2107:    "Red designada: ",
	s2108:    "2G",
	s2109:    "3G",
	s210a:    "4G",
	s210b:    "AUTO",
	s210c:    "Configuración de PIN",
	s210d:    "Se puede consultar el estado de la tarjeta SIM y configurar el PIN para la tarjeta SIM.",
	s210e:    "Estado de PIN:",
	s210f:    "Habilitar gestión de PIN",
	s2111:    "Deshabilitar PIN",
	s2112:    "Cambiar número de PIN",
	s2113:    "Eliminar el número de PIN guardado localmente",
	s2114:    "Código PUK:",
	s2115:    "Número de PIN:",
	s2116:    "Número de PIN anterior:",
	s2117:    "Número de PIN nuevo:",
	s2118:    "Confirmar número de PIN:",
	s2119:    "Intentos restantes:",
	s211a:    "Inserte una tarjeta SIM.",
	s211b:    "Tarjeta SIM obsoleta.",
	s211c:    "Tarjeta SIM bloqueada. Introduzca el código PUK correcto para restablecer el PIN y desbloquear la tarjeta SIM.",
	s211d:    "Introduzca el PIN correcto.",
	s211e:    "El PIN ha sido desbloqueado. Puede usar la tarjeta SIM para acceder a Internet. También puede realizar las siguientes operaciones:",
	s211f:    "Se ha deshabilitado la gestión de PIN.",
	s2120:    "El PIN debe contener 4 dígitos. Introduzca el PIN correcto.",
	s2121:    "El código PUK debe contener 8 dígitos. Introduzca el código PUK correcto.",
	s2122:    "El número de PIN de confirmación es diferente del número de PIN nuevo.",
	s2123:    "Tarjeta SIM no válida.",
	s0905:          'El sistema está ocupado. Vuelva a intentarlo más tarde.',
	s0e08:          'Aplicar',
	s0e09:          'Cancelar'
};
 
﻿var AcsstatusLgeDes = 
{
	s0100:          'Administración Remota',
	s0301:          'Esta página permite ver el estado de la conexión remota y el estado de aprovisionamiento del servicio.',
	s0302:          'Estado del informante:',
	s0303:          'Con éxito',
	s0304:          'No hay información',
	s0305:          'No hay respuesta',
	s0306:          'Información interrumpida',
	s0307:          'Estado desconocido',
	s0308:          'Estado de la conexión ACS:',
	s0309:          'Conexión remota exitosa',
	s030a:          'No hay solicitudes de conexión remota',
	s030b:          'Conexión remota interrumpida',
	s030c:          'Estado de aprovisionamiento del servicio:',
	s030d:          'Se está recibiendo la configuración del servicio remoto',
	s030e:          'Configuración exitosa',
	s030f:          'No se pudo configurar',
	s0310:          'No se aplicó la configuración del servicio remoto'

};
 
﻿
var AccountLgeDes =
{
	s0100:    "Esta página permite cambiar la contraseña de inicio de sesión de un usuario común, configurar la contraseña de autenticación del certificado SSL utilizada en el acceso al dispositivo por HTTPS e importar el certificado SSL correspondiente.",
	s0101:    "cambio de contraseña",
	s0102:    "Gestión de cuentas",
	s1902:    'El nivel de seguridad de la contraseña es muy bajo. Vuelva a configurarla.',
	s1904:    'La contraseña debe contener entre 1 y 127 caracteres.',
	s0f01:    'La contraseña del usuario común se cambió correctamente.',
	s0f02:    'La contraseña nueva no puede quedar vacía.',
	s0f03:    'La contraseña nueva debe contener de 9 a 30 caracteres.',
	s0f04:    'La contraseña nueva incluye un carácter no válido. Ingresar una contraseña válida.',
	s0f05:    'Ingresar una contraseña que tenga al menos uno de los siguientes caracteres especiales: \n: \ ! @ # $ { } [ ] . / \ ^ & * ( ) \\ \"',
	s0f06:    'La contraseña nueva no coincide con la contraseña confirmada.',
	s0f07:    'Esta página permite cambiar la contraseña del usuario común para garantizar la seguridad y para que sea fácil de recordar.',
	s0f08:    'Nombre de usuario:',
	s0f09:    'Contraseña nueva:',
	s0f0a:    '(entre 9 y 30 caracteres con al menos un carácter especial)',
	s0f0b:    'Confirmar contraseña:',
	s0f0c:    'Aplicar',
	s0f0d:    'Cancelar',
	s0f0e:    'La contraseña se cambió con éxito.',
	s0f0ea:   'Se modificó la contraseña. Deberá volver a iniciar sesión.',
	s0f0f:    'El campo de la contraseña anterior no puede quedar vacío.',
	s0f10:    'La contraseña anterior debe contener de 1 a 30 caracteres.',
	s0f11:    'La contraseña anterior no es correcta. Vuelva a intentarlo.',
	s0f12:    'Esta página permite cambiar la contraseña del usuario de la sesión actual para garantizar la seguridad y para que sea fácil de recordar.',
	s0f12a:   "Esta página permite cambiar la contraseña del usuario de la sesión actual para garantizar la seguridad y para que sea fácil de recordar,puede configurar el acceso ONT https contraseña de autenticación de certificado SSL y los certificados SSL de importación correspondientes.",
	s0f13:    'Contraseña anterior:',
	s0f14:    'Pista para recordar la contraseña:',
	s0f15:    'El campo de la pista para recordar la contraseña es obligatorio.',
	s1116:    '1. La contraseña debe contener al menos 6 caracteres.<br/>2. La contraseña debe contener al menos dos de las siguientes combinaciones: dígitos, mayúsculas, minúsculas, caracteres especiales (`~!@#$%^&*()-_=+\\|[{}];:\"\'<,.>/?).<br/>3. La contraseña debe ser distinta al nombre de usuario y a dicho nombre escrito al revés.',
	s1116a:   '1. La contraseña debe contener al menos 6 caracteres.<br/>2. La contraseña debe contener al menos dos de las siguientes combinaciones: dígitos, mayúsculas, minúsculas, caracteres especiales (`~!@#$%^&*()-_=+\\|[{}];:\"\'<,.>/?).<br/>3. La contraseña debe ser distinta al nombre de usuario y a dicho nombre escrito al revés.',
	ss1116b:  "1. Se recomienda que la contraseña contenga al menos seis caracteres.<br/>2. Se recomienda incluir al menos dos de los siguientes tipos de caracteres en la contraseña: dígitos, letras en mayúscula y minúscula y caracteres especiales.Los caracteres especiales pueden ser los siguientes: `~!@#$%^&*()-_=+|[{}];:'&lt;,.&gt;/?<br/>3. Se recomienda que la contraseña no sea el nombre de usuario ni este al revés.",
	ss1116c:  "1. Se recomienda que la contraseña contenga al menos seis caracteres.<br/>2. Se recomienda incluir al menos dos de los siguientes tipos de caracteres en la contraseña: dígitos, letras en mayúscula y minúscula y guiones bajos (_).<br/>3. Se recomienda que la contraseña no sea el nombre de usuario ni este al revés.",
	ss1116d:    '1. La contraseña debe contener al menos 8 caracteres.<br/>2. La contraseña debe contener al menos dos de las siguientes combinaciones: dígitos, mayúsculas, minúsculas, caracteres especiales (`~!@#$%^&*()-_=+\\|[{}];:\"\'<,.>/?).<br/>3. La contraseña debe ser distinta al nombre de usuario y a dicho nombre escrito al revés.',

	s1117:    'El nivel de seguridad de la contraseña es bajo. ¿Continuar?',
	s1118:    '<strong class=\"color_red\">La contraseña de inicio de sesión es la predeterminada. Cámbiela de inmediato.</strong>',

	s1119:    "Gestión de ONT",
	s1120:    "Cambiar contraseña de gestión",
	s1121:    "Guardar",
	s1122:    "Reiniciar y restablecer configuración",
	s1123:    "Reiniciar",
	s1124:    "Restablecer valores predeterminados",
	s1125:    "Haga clic aquí para reiniciar el dispositivo.",
	s1126:    "Haga clic aquí para restablecer la configuración predeterminada del terminal.",
	s1127:    "Restablecer valores predeterminados",

	s0d21:    'Aplicar',
	s0d22:    'Cancelar',

	s0d23:    'Habilitar la autenticación de certificado y establecer una contraseña.',
	s0d25:    'Habilitar autenticación de certificado:',
	s0d26:    'Contraseña de clave privada:',
	s0d28:    'Confirmar contraseña:',
	s0d29:    'Importar certificado',
	s0d2a:    'Certificado:',
	s0d2b:    'Buscar',
	s0d2c:    'Importar certificado',
	s0d10:    'Seleccionar una ruta del archivo.',
	s0d11:    'La longitud de la ruta del archivo no puede superar 128 caracteres.',
	s0d0f:    'La contraseña confirmada no es igual a la contraseña de la clave privada.',
	s0d14:    'La contraseña de la clave privada se cambió correctamente y se implementará después de reiniciar.',
	s1430:    "La contraseña es obligatoria. Vuelva a intentarlo.",
	s1901:    'Esta página permite configurar la contraseña de autenticación SSL utilizada para acceder a un ONT mediante HTTPS e importar el certificado SSL correspondiente. ',
	s1902:    'El nivel de seguridad de la contraseña es muy bajo. Vuelva a configurarla.',
	s1903:    'Gestión de certificados SSL',
	s1904:    'La contraseña debe contener entre 1 y 127 caracteres.',
	s1904a:   'La contraseña debe contener entre 8 y 64 caracteres.',
	s1905:    '(De 1 a 127 caracteres. Esta contraseña se implementará después de reiniciar el dispositivo).',

	s2000:    "Modifique la contraseña de inicio de sesión.",
	s2001:    "Anterior",
	s2002:    "Siguiente",
	s2003:    "Omitir",
	s2004:    "Salir",

	s2010:    "Requerimientos de contraseña",
	s2011:    "La contraseña debe contener al menos 6 caracteres.",
	ss2011a:  "La contraseña debe contener al menos 8 caracteres.",
	s2012:    "La contraseña debe contener al menos dos de las siguientes combinaciones: dígitos, mayúsculas, minúsculas, caracteres especiales (`~!@#$%^&*()-_=+\\|[{}];:\"\'<,.>/?).",
	s2013:    "La contraseña debe ser distinta al nombre de usuario y a dicho nombre escrito al revés.",
	
	s2201: "Cambio contraseña del router",
	s2202: "Desde aquí podrás cambiar la contraseña de acceso al router. Se recomienda que la clave tenga al menos 8 caracteres alfanuméricos:",
	s2203: "Contraseña anterior:",
	s2204: "Contraseña nueva:",
	s2205: "Confirmar nueva contraseña:",
	s2206: "Nivel de seguridad de la contraseña",
	s2207: "Su contraseña se ha modificado correctamente.",

	s2208: "Cerrar",
	s2209: "Aceptar",
	s220a: "Cancelar",

	s220b: "Baja",
	s220c: "Media",
	s220d: "Alta"
};
 
﻿
var ApmcfgLgeDes = 
{
	s0100: 	        'Administración avanzada de energia',
	s0e01:          'En esta página puede establecer el modo de ahorro de energía para el dispositivo.',
	s0e02:          'Modo de ahorro de energía',
	s0e03:          'Habilitar:',
	s0e04:          'Activar servicios en modo de batería',
	s0e05:          'Servicio',
	s0e06:          'Habilitado',
	s0e07:          'Gestión Remota:',
	s0e08:          'Aplicar',
	s0e09:          'Cancelar',
	s0e0a:			'VOZ:'
};
 
﻿
var BatteryinfoLgeDes = 
{ 
	s0101:          'Esta página permite ver la información sobre el modo de alimentación y la capacidad disponible de la batería.',
	s0102:          'Modo de alimentación:',
	s0103:          'Batería',
	s0104:          'Alimentación de red comercial',
	s0105:          'Capacidad disponible de la batería'
};
 
﻿
var BssLgeDes = 
{
	s0100:	        "Estado de aprovisionamiento del servicio",
	s1300:          "Esta página permite consultar el estado de aprovisionamiento del servicio.",
	s1301:          "Estado de registro del ONT:",
	s1302:          "--",
	s1303:          "El ONT se está registrando con el OLT. Espere.",
	s1304:          "El ONT se registró con el OLT." ,
	s1305:          "Actualizar",
	s1306:          "Finalizó el tiempo de espera para el registro del ONT con el OLT. Las causas posibles son: <br/>1. La fibra óptica no está conectada o la potencia óptica no es normal. <br/> 2. La información de autenticación de PON es incorrecta. <br/>Si la información mencionada es correcta, comuníquese con el centro de atención al cliente." ,
	s1307:          "Estado de configuración del servicio del OLT:",
	s1308:          "El OLT está implementando configuraciones. Espere.",
	s1309:          "Se configuró el servicio del OLT." ,
	s130a:          "Error al configurar el servicio del OLT." ,
	s130b:          "Error al obtener el estado. Motivo: la versión del OLT no coincide con el ONT.",
	s130c:          "Estado de configuración del EMS:",
	s130d:          "No se han emitido configuraciones de XML." ,
	s130e:          "El EMS está implementando configuraciones.",
	s130f:          "Se configuró el servicio del EMS.",
	s1310:          "Error al configurar el servicio del EMS.",
	s1311:          "Estado de registro del ACS:",
	s1312:          "El ONT está esperando para registrarse con el servidor ACS. Espere.",
	s1313:          "El ONT se está registrando con el servidor ACS. Espere.",
	s1314:          "Se registró con el servidor ACS." ,
	s1315:          "Error al registrarse con el servidor ACS.",
	s1316:          "El ONT no es compatible con el OLT. Reemplace el ONT.",
	s1317:          "Obteniendo estado... Espere.",
	
	s2000:"Configuración realizada. Proporcionando servicios...",
	s2001:"Volver a la Página de inicio",
	s2002:"El ONT se está registrando en el OLT... Espere.",
	s2003:"Servicios proporcionados. Bienvenidos.",
	s2004:"El EMS está proporcionando la configuración... Espere.",
	s2005:"Error de configuración del servicio en el EMS. Verificar la configuración del EMS.",
	s2006:"Registrado en el ACS.",
	s2007:"El ONT se está registrando en el servidor ACS... Espere.",
	s2008:"Error de registro del ONT en el ACS.",
	s2009:"Finalizó el tiempo de espera para el registro del ONT con el OLT. Las causas posibles son: <br/>1. La fibra óptica no está conectada o la potencia óptica no es normal. <br/> 2. La información de autenticación de PON es incorrecta. <br/>Si la información mencionada es correcta, comuníquese con el centro de atención al cliente.",
	s2010:"Error de configuración del servicio en el OLT.",
	s2011:"El OLT está proporcionando la configuración. Espere.",
	s2012:"Error al obtener el estado porque la versión del OLT no coincide.",
	s2013:"Aprovisionamiento del servicio incompleto. Vaya a la página de inicio y haga clic en la pestaña Estado de aprovisionamiento del servicio, que se encuentra a la izquierda de la página, para obtener información de aprovisionamiento del servicio."
};
 
﻿
var CfgfileLgeDes = 
{ 
	s0100:			"Esta página permite guardar, descargar y actualizar el archivo de configuración.",
	s0101:			"Guardar configuración y reiniciar",
	s0102:          "Administración de archivo de configuración",
	s0905:          'El sistema está ocupado. Vuelva a intentarlo más tarde.',
	s0701:          'Se guardó correctamente.',
	s0702:          'El campo de la ruta del archivo no puede quedar vacío.',
	s0703:          'La longitud de la ruta no puede exceder los 128 caracteres.',
	s0704:          'El archivo es demasiado grande.',
	s0705:          'El archivo no es válido o no existe.',
	s0706:          'Está seguro de que desea guardar las configuraciones o reiniciar el terminal?',
	s0707:          'Esta página permite guardar los archivos de configuración actual en la memoria Flash y/o reiniciar el dispositivo.',
	s0709:          'Guardar la configuración',
	s070a:          'Guardar y reiniciar',
	s070b:          'Se pueden descargar los archivos de la configuración actual en la PC local.',
	s070c:          'Descargar el archivo de configuración',
	s070d:          'Si se ingresa la ruta del archivo de configuración y se hace clic en Actualizar archivo de configuración, la terminal se actualizará con el archivo de configuración guardado.',
	s070e:          'Archivo de configuración:',
	s070f:          'Buscar ',
	s0710:          'Actualizar archivo de configuración',
	s0711:	        'Si se importa el archivo de configuración, el terminal se reiniciará y dicho archivo se implementará. ¿Confirma importar el archivo de configuración?',
	
	s0a01:          'Si se restablece la configuración predeterminada, se perderán los datos configurados por el usuario y el dispositivo se reiniciará. ¿Está seguro de continuar?',
	s0a02:          'Esta página permite restablecer la configuración predeterminada.',
	s0a03:          'Restablecer a valores predeterminados'
};
 
﻿
var CfgguideLgeDes = 
{ 
	s1116:          '1. La contraseña debe contener al menos 6 caracteres.<br/>2. La contraseña debe contener al menos dos de las siguientes combinaciones: dígitos, mayúsculas, minúsculas, caracteres especiales (´~!@#$%^&*()-_=+\\|[{}];:\"\'<,.>/?).<br/>3. La contraseña debe ser distinta al nombre de usuario y a dicho nombre escrito al revés.',
	s0f0f:          'El campo de la contraseña anterior no puede quedar vacío.',
	s0f02:          'La contraseña nueva no puede quedar vacía.',
	s0f04:          'La contraseña nueva incluye un carácter no válido. Ingresar una contraseña válida.',
	s0f06:          'La contraseña nueva no coincide con la contraseña confirmada.',
	s0f11:          'La contraseña anterior no es correcta. Vuelva a intentarlo.',
	s1902:	  'El nivel de seguridad de la contraseña es muy bajo. Vuelva a configurarla.',
	s1904:    'La contraseña debe contener entre 1 y 127 caracteres.',

	s2000:    	"Método de aprovisionamiento del servicio",
	s2001:    	"En el OLT",
	s2002:    	"Los servicios del ONT se configuran en el OLT.",
	s2003:    	"En el EMS",
	s2004:    	"Los servicios del ONT se configuran en el EMS.",
	s2005:    	"En el ACS",
	s2006:    	"Los servicios del ONT se configuran en el ACS.",
	s2007:    	"En la página web del ONT",
	s2008:    	"Los servicios del ONT se configuran en la página web del ONT.",
	s2009:    	"Salir",
	s2010:    	"Siguiente",
	s2011:    	"Copyright © Tecnologias Huawei Co., Ltd 2009-2016. Todos los derechos reservados.",
	
	s2012:    	"Presentamos el ONT Huawei, que permite conectarse con familiares y amigos.",
	s2013:    	"Autenticación de ONT",
	s2014:    	"Configuración de WAN",
	s2015:    	"Finalización de configuración",
	
	s2016:    	"Configuración de Internet",
	s2017:    	"Configuración de Wi-Fi",
	s2018:    	"Gestión de cuentas",
	
	s2019:    	"Configuración realizada. Bienvenidos.",
	s2020:    	"Anterior",
	s2021:    	"Volver a la Página de inicio",
	
	s2040:      "Modo de conexión de red actual: ",
	s2041:      "Por cable",
	s2042:      "Wi-Fi",
	s2043:      "Si modificó los parámetros de Wi-Fi, intente volver a conectarse.",
	s2044:      "Es posible acceder a la página de inicio y comenzar a usar el ONT."
};
 
﻿
var CollectInfoLgeDes = 
{ 
	s1101:			"Información de fallas recopilada",
	s1102:          "Esta página permite recopilar y descargar la información de fallas.",	
	s1104:	        "Iniciar",
	s1114:          "Descargar",
	s1119:          "Recopilando información de fallas... Espere.",
	s1120:          "Se recopiló la información de fallas."
};
 
﻿
var DebuglogviewLgeDes = 
{ 
	s0100:          "Esta página permite descargar y consultar registros de depuración.",
	s0101:    		"Registro de depuración",
	s0b0f:          'Descargar o revisar el log',
	s0b10:          'En esta opción se podrá visualizar y descargar el Log.',
	s0b11:          'Descargar Archivo del log'
};
 
﻿var DevInfoDes =  
{                              
	s0200:    "Información del dispositivo",
	s0201:          'En esta página, puede consultar información básica sobre la terminal.',
	s0202:          'Nombre del Producto:',
	s0203:          'Descripción:',
	s0204:          'Versión de hardware:',
	s0205:          'Versión de software:',
	s0206:          'Estado de registro de la ONT:',
	s0207:          'Identificador de la ONT:',
	s0208:          'Utilización de la CPU:',
	s0209:          'Utilización de memoria:',
	s020a:          'Alias de XML:',
	s020c:          'Registrado y autorizado',
	s020d:          'Registrado y no autorizado',
	s020e:          'Tiempo de operación del dispositivo:',
	s020f:          ' día/s ',
	s0210:          ' hora/s ',
	s0211:          ' minutos ',
	s0212:          ' segundos ',
	s0213:          ' días ',
	s0214:          ' horas ',
	s0215:          ' minuto/s ',
	s0216:          ' segundo/s ',
	s0217:          'Info de fabricación:',
	s0218:          ' (estado inicial)',
	s0219:          ' (Estado en espera)',
	s0220:          ' (Estado Número de Serie)',
	s0221:          ' (Estado de Ranging)',
	s0222:          ' (Estado de Operación)',
	s0223:          ' (Estado POPUP)',
	s0224:          ' (Estado de Emergencia-Detenido)',
	s0225:          'Info personalizada:',
	s0226:    		'Fecha y hora del sistema:',
	s1321:    "El ONT no es compatible con el OLT. Reemplace el ONT.",
	s1322:    "(Estado inicial)",
	s1323:    "(estado en espera)",
	s1324:    "(estado de número de serie)",
	s1325:    "(estado del rango)",
	s1326:    "(estado de operación)",
	s1327:    "(estado EMERGENTE)",
	s1328:    "(estado de interrupción de emergencia)",
	s1611:"Número de Serie:",
	s1612:"Mac:&nbsp;",
	s2016:    "El administrador está utilizando la contraseña inicial. Si desea modificarla, comuníquese con la operadora de telecomunicaciones. Para obtener más detalles sobre cómo cambiar la contraseña, consulte la sección de Mantenimiento de seguridad en http://support.huawei.com."
};
                   
﻿
var DlnaLgeDes =
{
	s0526:'Aplicar',
	s0527:'Cancelar',
	s0531:"Precaución:",
	s0532:"No extraer y volver a insertar el dispositivo USB cuando está en uso, pueden dañarse los archivos almacenados.",
	s1410:"Ruta de uso compartido:",
	s1436:"Directorio de búsqueda",
	s1600:"El servicio de uso compartido de medios permite compartir información multimedia con dispositivos que soporten DLNA. Por ejemplo, es posible compartir videos, audio e imágenes con PC, dispositivos móviles y equipos electrónicos. Esta página permite configurar la selección del servicio de uso compartido y compartir directorios.",
	s1601:"Habilitar uso compartido de medios:",
	s1602:"Ruta de uso compartido:",
	s1603:"Todas las rutas",
	s1604:"Especificar ruta",
	s1605:"Examinar...",
	s1606:"Se pueden configurar hasta 10 rutas de uso compartido.",
	s1607:"La ruta es obligatoria. Especifique una ruta.",
	s1608:"La ruta ya está en la lista. Ingrese otra.",
	s1609:"Ruta especificada:",
	s1610:"La ruta del directorio especificado es demasiado larga.",
	s1611:"Uso compartido de medios"
};
 
﻿
var FirmwareLgeDes = 
{
	s0900:	  		"Actualización de software",
	s0901:          'Seleccionar un archivo de firmware.',
	s0902:          'La longitud de la ruta del archivo de firmware no puede superar 128 caracteres.',
	s0903:          'El firmware es demasiado grande.',
	s0904:          ' no es válido o no existe.',
	s0905:          'El sistema está ocupado. Vuelva a intentarlo más tarde.',
	s0906:          'Esta página permite actualizar el Firmware de la ONT.',
	s0906a:         'Esta página permite usar la actualización del archivo de versión para actualizar la versión de software del terminal a la versión deseada. Si habilita la actualización automática, el terminal actualiza automáticamente la versión de firmware desde el servidor remoto.',
	s0907:          'Archivo de firmware:',
	s0908:          'Buscar ',
	s0909:          'Actualizar',
	s090a:"Configuración de actualización automática",
	s090b:"Actualización local",
	s090c:"Habilitar actualización automática"
};
 
﻿
var LedcfgLgeDes = 
{
	s0100: 	  "Configuración del switch de indicadores", 
	s0e08:          'Aplicar',
	s0e09:          'Cancelar',
	s1500:	  "Esta página permite configurar el switch de indicadores de un dispositivo. El período de apagado del indicador se puede ajustar configurando Switch de indicadores como Apagado. Los indicadores siempre están apagados si no se especifica el período de apagado correspondiente.",
	s1501:    "Configuración del switch de indicadores",
	s1801:    "Hora de inicio",
	s1802:    "Hora de finalización",
	s1803:    "Switch de indicadores",
	s1804:    "Período de apagado del indicador",
	s1805:    ":",
	s1806:    "(00:00-23:59)",
	s1807:	  'La cantidad configurada de períodos alcanzó el límite máximo permitido. No se pueden agregar más períodos.',
	s1808:    "Encendido",
	s1809:	  'Apagado',
	s1810:	  'Hora de inicio no válida.',
	s1811:	  'Hora de finalización no válida.',
	s1812:	  'La hora ingresada no es válida. Ingrese un valor dentro del rango de 00 a 23.',
	s1813:	  'Los minutos ingresados no son válidos. Ingrese un valor dentro del rango de 00 a 59.',
	s1814:	  'El período especificado no es válido. La hora de inicio debe ser anterior a la de finalización. ',
	s1815:	  'No se configuró ninguna regla de períodos.',
	s1816:	  'Especifique un período.',
	s1817:	  'El período especificado se superpone con un período ya configurado. Especifique otro período.',
	s1818:	  'Configuración del período de apagado del indicador'

};
 
var PrompterDes = 
{ 
	s1005:          'Error de actualización. Seleccione el archivo correcto y vuelva a intentarlo. Nota: No se puede actualizar el dispositivo si el tipo de archivo seleccionado es incorrecto.',
	s1006:          'No se pudo restablecer la configuración predeterminada.',
	s1007:          'La configuración fue restablecida correctamente, y el sistema se está reiniciando. Espere...',
	s1008:          'La configuración actual del dispositivo es igual a la configuración predeterminada.',
	s1009:          'Actualización exitosa. Haga clic en el botón para reiniciar el dispositivo y activar el archivo.',
	s1010:          'Reiniciar',
	s1011:          '¿Está seguro de reiniciar el dispositivo?',
	s1012:          'Error al actualizar el archivo de configuración. Seleccione el archivo correcto y vuelva a intentarlo.',
	s1015:          'Inténtelo nuevamente',
	s1316:    "Error al hacer backup del archivo de configuración en el dispositivo USB.",
	s1317:    "Se hizo backup del archivo de configuración en el dispositivo USB.",
	s1318:    "Error al importar el certificado. Seleccione el archivo correcto y vuelva a intentarlo.",
	s1319:    "Se importó el certificado.",
	s131a:    "Se actualizó el archivo de configuración. El sistema se está reiniciando. Espere.",
	s131b:    "Error al descargar el archivo. Causas posibles:<br>1. El archivo no existe.<br>2. Los parámetros no se configuraron correctamente.<br>3. El sistema está ocupado.",
	s131c:    "Error al restablecer la configuración predeterminada.",
	s131d:    "Se restableció la configuración. El sistema se está reiniciando. Espere.",
	s131e:    "La configuración actual del dispositivo es igual a la configuración predeterminada.",
	s131f:    "Se actualizó. Haga clic en el botón para reiniciar el dispositivo y activar el archivo.",
	s1320:    "¿Confirma reiniciar el dispositivo?",
	s1321:    "Aviso: No se pudo iniciar sesión porque la cantidad de usuarios de la sesión supera el umbral o porque el usuario ya inició sesión."
};
 
﻿var SmartDiagnoseLgeDes = 
{
	s1900:    	'La conexión de Internet no es normal',
	s1901:      'RF module chip fault.',
	s1902:      'DECT chip fault',
	s2000:	    'SD5113 chip fault.',
	s2001:      'Wi-Fi chip fault.',
	s2002:		'LSW chip fault.',
	s2003:		'Codec chip fault.',
	s2004:		'Optical module chip fault.',
	s2005:		'PHY chip fault.',
	s2006:		'MAC chip forwarding is abnormal; ',
	s2007:		'PHY chip forwarding is abnormal; ',
	s2008:		'El hardware del ONT es normal',
	s2009:		'El hardware del ONT es anormal',
	s2010:    	'La conexión a Internet es normal',
	s2011:    	'Error de conexión dial-up PPPoE',
	s2012:    	'Error de conexión dial-up DHCP',
	s2013:    	'Estado de conexión a Internet',
	s2014:    	'Estado del hardware del ONT',
	
	s2015:    	'Diagnóstico con un clic',	
	s2016:    	'Diagnosticando...',
	s2017:    	'El resultado del diagnóstico es normal.',	
	s2018:    	'El resultado del diagnóstico es anormal. Solucionar la anormalidad.',	
	s2019:    	'Volver a diagnosticar',	
	s2020:    	'Nivel de seguridad de la contraseña',	
	s2021:    	'Nivel de seguridad de la contraseña del usuario',
	s2022:    	'Bajo',
	s2023:    	'Alto',	
	s2024:    	'Nivel de seguridad de la contraseña de Wi-Fi',
	s2025:      'El trayecto óptico es normal.',
	s2026:      'El trayecto óptico es anormal. Verifique las conexiones de fibra óptica.',
	s2027:      'Registrado en el OLT.',
	s2028:      'Error al registrar en el OLT. Verifique los parámetros de registro.',
	s2029:      'Este método de diagnóstico esta destinado solo a ingenieros profesionales y afecta a los servicios de datos. Por lo tanto, sea cuidadoso al usar este método. ',
	
	s3000:      'Estado del servicio de voz',
	s3001:      'Normal',
	s3002:      'Puerto',
	s3003:      'Probando...',
	s3004:      'No hay ningún servicio de voz configurado',
	s3005:      'Servicio de voz cerrado',
	s3006:      'Error al registrar',
	s3007:      'Resultado de prueba de bucle anormal',
	s3008:      'Conexión de red de voz anormal',
	s3009:      'error desconocido',
	s3010:      'La prueba de bucle no se lleva a cabo porque otros puertos están siendo utilizado para llamadas',
	
	s3014: 		'Estado del servicio IPTV del gateway',
	s3015: 		'El estado del puerto integrado del decodificador es normal',
	s3016: 		'El estado del puerto del decodificador integrado no es normal. Comuníquese con el operador para obtener asistencia.',
	s3017: 		'El estado de las configuraciones de IPTV es normal',
	s3018: 		'Las configuraciones de IPTV del gateway son incorrectas. Verifique las configuraciones del puerto WAN.',
	s3019: 		'El estado de la red IPTV del gateway es normal.',
	s3020: 		'La red de IPTV del gateway no es normal. Verifique el estado de la conexión del puerto WAN.',
	s3021: 		'El servicio IPTV del gateway es normal. ',
	s3022: 		'El decodificador integrado no tiene tráfico.',
	s3023:      'El modo de marcación PPPoE es manual. Marque manualmente. '

};
 
﻿var ResetLgeDes = 
{  
	s0601:          'Los datos no guardados se perderán. ¿Está seguro de reiniciar el dispositivo?',
	s0602:          'Esta página permite reiniciar el dispositivo.',
	s0603:          'Reiniciar'
};
 
﻿var RestoreLgeDes = 
{
	s0a01:          'Si se restablece la configuración predeterminada, se perderán los datos configurados por el usuario y el dispositivo se reiniciará. ¿Está seguro de continuar?',
	s0a02:          'Esta página permite restablecer la configuración predeterminada.',
	s0a03:          'Restablecer a valores predeterminados',
	s0a04:	  "¿Desea restablecer las configuraciones IoT? De ser así, debe reinstalar los sensores de a uno.",
	s0a05:	  "Restablecer las configuraciones IoT",
	s0a06:	  "Aplicar",
	s0a07:	  "Cancelar"
};
 
var SambaLgeDes =
{
	ss1116b:    "1. Se recomienda que la contraseña contenga al menos seis caracteres.<br/>2. Se recomienda incluir al menos dos de los siguientes tipos de caracteres en la contraseña: dígitos, letras en mayúscula y minúscula y caracteres especiales.Los caracteres especiales pueden ser los siguientes: `~!@#$%^&*()-_=+|[{}];:'&lt;,.&gt;/?<br/>3. Se recomienda que la contraseña no sea el nombre de usuario ni este al revés.",
	ss1116c:    "1. Se recomienda que la contraseña contenga al menos seis caracteres.<br/>2. Se recomienda incluir al menos dos de los siguientes tipos de caracteres en la contraseña: dígitos, letras en mayúscula y minúscula y guiones bajos (_).<br/>3. Se recomienda que la contraseña no sea el nombre de usuario ni este al revés.",
	s0526:      'Aplicar',
	s0527:      'Cancelar',
	s0531:      "Precaución:",
	s0532:      "No extraer y volver a insertar el dispositivo USB cuando está en uso, pueden dañarse los archivos almacenados.",
	s1400:      "Esta página permite habilitar la impresora residencial y el uso compartido del almacenamiento.<br/>Antes de habilitar la impresora residencial, conéctela al gateway residencial a través de un puerto USB. La impresora y el gateway residenciales comparten una dirección IP. Busque la impresora e instale el controlador. La impresora está lista para ser usada.",
	s1401:      "Habilitar impresora y uso compartido de almacenamiento:",
	s1402:      "Información de la impresora residencial:",
	s1403:      "Habilitar autenticación de uso compartido:",
	s1404:      "Configuración de la cuenta",
	s1405:      "Detalles",
	s1406:      "Nombre de usuario:",
	s1407:      "Contraseña:",
	s1408:      "Habilitar:",
	s1409:      "Permiso:",
	s1410:      "Ruta de uso compartido:",
	s1411:      "Directorio:",
	s1412:      "¿Confirma eliminar el usuario?",
	s1413:      "ID",
	s1414:      "Nombre de usuario",
	s1415:      "Estado",
	s1416:      "Permiso",
	s1417:      "Ruta de uso compartido",
	s1418:      "Habilitar",
	s1419:      "Deshabilitar",
	s1420:      "Solo lectura",
	s1421:      "Lectura/Escritura",
	s1422:      "Ocultar",
	s1423:      "Todas las rutas",
	s1424:      "Especificar ruta",
	s1425:      "Buscar",
	s1426:      "El nombre de usuario es obligatorio. Vuelva a intentarlo.",
	s1427:      "El nombre de usuario no puede ser un nombre de usuario especial utilizado por el sistema ni un nombre de un proceso. Vuelva a intentarlo.",
	s1428:      "El nombre de usuario ya existe. Vuelva a intentarlo.",
	s1429:      "Nombre de usuario no válido. El nombre de usuario solo puede contener letras en minúscula, dígitos y guiones bajos. ",
	s1430:      "La contraseña es obligatoria. Vuelva a intentarlo.",
	s1431:      "La ruta del usuario del servicio de almacenamiento es obligatoria.",
	s1432:      "Se pueden configurar hasta 8 usuarios.",
	s1433:      "Dispositivo de almacenamiento USB:",
	s1434:      "Volver",
	s1435:      "Aceptar",
	s1436:      "Directorio de búsqueda",
	s1437:      "Contraseña no válida. Vuelva a intentarlo.",
	s1438:      "El nombre de usuario no puede comenzar con un dígito. Vuelva a intentarlo.",
	s1439:      "El nivel de seguridad de la contraseña es bajo. ¿Continuar?",
	s1440:      "La contraseña solo puede contener letras, dígitos y guiones bajos (_).",
	s1441:      "La ruta es demasiado larga.",
	s1442:      "El nivel de seguridad de la contraseña es bajo. Ingrese otra contraseña.",
	s1443:      "Error al obtener la ID de partición del disco lógico. Actualice la página e inténtelo nuevamente.",
	s1444:      "Uso compartido residencial por USB",
	s1445:      "Uso compartido residencial"
};
 
﻿var SmartOntdes =
{
	smart001:"Info de PON",
	smart002:"Estado de la conexión:",
	smart003:"Conectado",
	smart004:"Desconectado",
	smart005:"Duración de la conexión:",
	smart006:"h",
	smart007:"min",
	smart008:"s",
	smart009:"Estado de registro de gateway",
	smart010:"Trayecto óptico (OLT):",
	smart011:"Sin autenticar",
	smart012:"Autenticado",
	smart013:"Error al autenticar",
	smart014:"Estado de registro (ACS):",
	smart015:"Sin registrar",
	smart016:"Registrado",
	smart017:"Error al registrar",
	smart018:"Estado de la conexión de red",
	smart019:"Protocolo IP:",
	smart020:"Dirección IP:",
	smart021:"Protocolo de línea:",
	smart022:"Succeeded",
	smart023:"Not reported",
	smart024:"No response",
	smart025:"Interrupted",
	smart026:"Unknown",
	smart027:"Dirección IPv4:",
	smart028:"Dirección IPv6:",
	smart029:"La fibra está desconectada."
};
 
﻿var SntpLgeDes =
{
	s0c01: 'El período de sincronización de fecha y hora debe ser superior a 0.',
	s0c02: 'Período de sincronización de fecha y hora no válido.',
	s0c03: 'El segundo cuadro de texto del servidor SNTP primario no puede quedar vacío cuando se selecciona "Otro" en el primer campo.',
	s0c04: 'El formato de dirección IP del servidor DNS primario no es correcto.',
	s0c05: 'La dirección IP del servidor SNTP primario no es válida. Ingresar una dirección unicast.',
	s0c06: 'La dirección del servidor SNTP primario no es válida.',
	s0c07: 'El segundo cuadro de texto del servidor SNTP secundario no puede quedar vacío cuando se selecciona "Otro" en el primer campo.',
	s0c08: 'El formato de dirección IP del servidor SNTP secundario no es correcto.',
	s0c09: 'La dirección IP del servidor SNTP secundario no es válida. Ingresar una dirección unicast.',
	s0c0a: 'La dirección del servidor SNTP secundario no es válida.',
	s0c0b: 'Los cambios en el huso horario se implementarán solo después de reiniciar el dispositivo.',
	s0c0c: 'El campo de configuración no puede quedar vacío.',
	s0c0d: 'Error de formato de tiempo.',
	s0c0e: 'Se debe especificar tanto la fecha y hora de inicio como de finalización.',
	s0c0f: 'Esta página permite configurar el protocolo SNTP, la zona horaria y el horario de verano para obtener la hora exacta.',
	s0c10: 'Sincronizar automáticamente del servidor la fecha y hora',
	s0c11: 'Servidor SNTP primario:',
	s0c12: 'Servidor SNTP secundario:',
	s0c13: 'Zona horaria:',
	s0c14: 'Período de sincronización de fecha y hora:',
	s0c15: '(s)',
	s0c16: 'Nombre de WAN:',
	s0c17: 'Aplicar',
	s0c18: 'Cancelar',
	s0c19: 'Habilitar horario de verano',
	s0c1a: 'Fecha y hora de inicio del horario de verano:',
	s0c1b: 'Enero',
	s0c1c: 'Febrero',
	s0c1d: 'Marzo',
	s0c1e: 'Abril',
	s0c1f: 'Mayo',
	s0c20: 'Junio',
	s0c21: 'Julio',
	s0c22: 'Agosto',
	s0c23: 'Septiembre',
	s0c24: 'Octubre',
	s0c25: 'Noviembre',
	s0c26: 'Diciembre',
	s0c27: 'Primero',
	s0c28: 'Segundo',
	s0c29: 'Tercero',
	s0c2a: 'Cuarto',
	s0c2b: 'Último',
	s0c2c: 'Domingo',
	s0c2d: 'Lunes',
	s0c2e: 'Martes',
	s0c2f: 'Miércoles',
	s0c30: 'Jueves',
	s0c31: 'Viernes',
	s0c32: 'Sábado',
	s0c33: 'Hora/s:',
	s0c34: '',
	s0c35: 'Minuto/s:',
	s0c36: '',
	s0c37: 'Segundo/s:',
	s0c38: '',
	s0c39: 'Fecha y hora de finalización del horario de verano:',
	s0c40: 'Fecha y hora actuales:',
	s0c41: 'La fecha de inicio y la fecha de finalización del horario de verano no pueden estar en un mismo mes.',
	s0c42: "Validar segmentos de tiempo personalizados",
	s0c43: "Día",
	s0c44: "Segmento de tiempo",
	s0c45: "Indicador global que deshabilita el segmento de tiempo",
	s0c46: "Sí",
	s0c47: "Indicador personalizado que deshabilita el segmento de tiempo",
	s0c48: "Deshabilitar el indicador",
	s0c49: "Ajuste de la hora",
	s0c4a: 'El segundo cuadro de texto del servidor SNTP terciario no puede quedar vacío cuando se selecciona "Otro" en el primer campo.',
	s0c4b: 'El formato de dirección IP del servidor SNTP terciario no es correcto.',
	s0c4c: 'La dirección IP del servidor SNTP terciario no es válida. Ingresar una dirección unicast.',
	s0c4d: 'La dirección del servidor SNTP terciario no es válida.',
	s0c4e: 'El segundo cuadro de texto del servidor SNTP cuaternario no puede quedar vacío cuando se selecciona "Otro" en el primer campo.',
	s0c4f: 'El formato de dirección IP del servidor SNTP cuaternario no es correcto.',
	s0c50: 'La dirección IP del servidor SNTP cuaternario no es válida. Ingresar una dirección unicast.',
	s0c51: 'La dirección del servidor SNTP cuaternario no es válida.',
	s0c52: 'Servidor SNTP terciario:',
	s0c53: 'Servidor SNTP cuaternario:',
	s0c54: "Aviso:",
	s0c55: "Si los ajustes se configuran de forma incorrecta, esto puede afectar los servicios relacionados con fecha y hora. Por lo tanto, se recomienda conservar los ajustes predeterminados."

};
 
﻿var SoftNoticeDes =  
{  
	s2001:    "Esta página contiene información del software de código abierto del dispositivo.",
	s2002:    "AVISO ACERCA DEL SOFTWARE DE CÓDIGO ABIERTO",
	s2003:    "Este documento contiene un aviso de software de código abierto para este producto. Las licencias de software de código abierto se otorgan a los titulares de derechos respectivos. Las licencias de código abierto tienen prelación en relación con toda otra información de licencia del software de código abierto del producto.",
	s2004:    "Exclusión de garantías",
	s2005:    "EL SOFTWARE DE CÓDIGO ABIERTO DE ESTE PRODUCTO SE DISTRIBUYE CON LA INTENCIÓN DE QUE SEA ÚTIL. SIN EMBARGO, NO SE OTORGA GARANTÍA ALGUNA EN RELACIÓN A ESTE, NI SIQUIERA LA GARANTÍA IMPLÍCITA DE COMERCIABILIDAD O APTITUD PARA UN FIN ESPECÍFICO. PARA OBTENER MÁS DETALLES, CONSULTE LAS LICENCIAS CORRESPONDIENTES.",
	s2006:    "Información del software de código abierto",
	s2007:    "Software",
	s2008:    "Versión",
	s2009:    "Aviso de copyright",
	s2010:    "Licencia",
	s2011:    "Enlace de la licencia",
	s2012:    "Oferta escrita",
	s2013:    "Este producto contiene software sobre el cual los titulares de los derechos otorgan una licencia de conformidad con los términos de la Licencia General Pública (GNU), versión 2 (GPLv2) u otras licencias de software de código abierto. Le brindaremos a usted y a terceros el código fuente del software objeto de la licencia de software de código abierto si nos envía una solicitud escrita por correo postal/correo electrónico a las siguientes direcciones:<br/>foss@huawei.com<br/>Deberá especificar el nombre del producto y la versión de firmware para la cual necesita el código fuente. Deberá indicar también un medio de contacto.<br/><br/><span class=copyrightinfo_title_bold>TENGA EN CUENTA QUE DEBERÁ PAGAR EL COSTO DERIVADO DE LA TRANSMISIÓN DE DATOS Y EL CORREO POSTAL GENERADO POR EL ENVÍO DE LOS DATOS. ESTA OFERTA ES VÁLIDA POR EL PLAZO DE TRES AÑOS DESDE EL MOMENTO DE LA DISTRIBUCIÓN DEL PRODUCTO Y SIEMPRE QUE OFREZCAMOS REPUESTOS O EL SERVICIO DE SOPORTE TÉCNICO PARA EL MODELO DE PRODUCTO PERTINENTE.</span>",
	s2014:    "Aviso acerca del software de código abierto",
	s2050:    "Textos de licencias y aviso de Copyright"
};
 
﻿var WebcertmgntLgeDes = 
{ 	
	s0d21:          'Aplicar',
	s0d22:          'Cancelar',
	s0d23:          'Habilitar la autenticación de certificado y establecer una contraseña.',
    s0d25:          'Habilitar autenticación de certificado:',
	s0d26:          'Contraseña de clave privada:',
    s0d28:          'Confirmar contraseña:',
	s0d29:          'Importar certificado',
    s0d2a:          'Certificado:',
	s0d2b:          'Buscar',
	s0d2c:          'Importar certificado',
	s0d10:          'Seleccionar una ruta del archivo.',
	s0d11:          'La longitud de la ruta del archivo no puede superar 128 caracteres.',
	s0d0f:          'La contraseña confirmada no es igual a la contraseña de la clave privada.',
	s0d14:          'La contraseña de la clave privada se cambió correctamente y se implementará después de reiniciar.',
	s1430:		"La contraseña es obligatoria. Vuelva a intentarlo.",
	s1116:          '1. La contraseña debe contener al menos 6 caracteres.</br>2. La contraseña debe contener al menos dos de las siguientes combinaciones: dígitos, mayúsculas, minúsculas, caracteres especiales (`~!@#$%^&*()-_=+\\|[{}];:\"\'<,.>/? y espacio).</br>3. La contraseña debe ser distinta al nombre de usuario y a dicho nombre escrito al revés.',
	s1901:	  'Esta página permite configurar la contraseña de autenticación SSL utilizada para acceder a un ONT mediante HTTPS e importar el certificado SSL correspondiente. ',
	s1902:	  'El nivel de seguridad de la contraseña es muy bajo. Vuelva a configurarla.',
	s1903:	  'Gestión de certificados SSL',
	s1904:    'La contraseña debe contener entre 1 y 127 caracteres.',
	s1905:    '(De 1 a 127 caracteres. Esta contraseña se implementará después de reiniciar el dispositivo).'
};
 
﻿var Tr069LgeDes =  
{
	s0100:        "Esta página permite configurar los parámetros del ACS, configurar la contraseña de autenticación con un certificado SSL e importar el certificado SSL requerido.",
	s0101:        "Configuración del ACS",
	s1116:          '1. La contraseña debe contener al menos 6 caracteres.<br/>2. La contraseña debe contener al menos dos de las siguientes combinaciones: dígitos, mayúsculas, minúsculas, caracteres especiales (`~!@#$%^&*()-_=+\\|[{}];:\"\'<,.>/? y espacio).<br/>3. La contraseña debe ser distinta al nombre de usuario y a dicho nombre escrito al revés.',
	s1430:		"La contraseña es obligatoria. Vuelva a intentarlo.",
	s1902:	  'El nivel de seguridad de la contraseña es muy bajo. Vuelva a configurarla.',                  
	s0d01:          'Ingresar una URL.',
	s0d02:          'La URL de ACS no debe contener espacios ni los siguientes caracteres: \n\< > \' \" { } [ ] % \\ ^ # |\"',
	s0d03:          'Intervalo informado no válido.',
	s0d04:          'Fecha/hora informados no válidos.',
	s0d05:          'Ingresar un nombre de usuario ACS.',
	s0d06:          'Nombre de usuario ACS no válido.',
	s0d07:          'Ingresar la contraseña de ACS.',
	s0d08:          'La contraseña de ACS no es válida.',
	s0d09:          'Ingresar un nombre de usuario de solicitud de conexión.',
	s0d0a:          'El nombre de usuario de la solicitud de conexión no es válido.',
	s0d0b:          'Ingresar la contraseña de la solicitud de conexión.',
	s0d0c:          'La contraseña de la solicitud de conexión no es válida.',
	s0d0d:          'DSCP no válido.',
	s0d0e:          'La contraseña debe contener entre 1 y 32 caracteres.',
	s0d0f:          'La contraseña confirmada no es igual a la contraseña de la clave privada.',
	s0d10:          'Seleccionar una ruta del archivo.',
	s0d11:          'La longitud de la ruta del archivo no puede superar 128 caracteres.',
	s0d12:          'El archivo es demasiado grande.',
	s0d13:          ' no es válido o no existe.',
	s0d14:          'La contraseña de la clave privada se cambió correctamente y se implementará después de reiniciar.',
	s0d15:          'Configuración de los parámetros de ACS',
	s0d16:          'Si la función de autoaprovisionamiento de TR069 está habilitada, se pueden configurar los parámetros de ACS de la terminal.',
	s0d17:          'Habilitar informe periódico:',
	s0d18:          'Intervalo del informe:',
	s0d19:          'Fecha/Hora del informe:',
	s0d1a:          'aaaa-mm-ddThh:mm:ss (por ejemplo, 2009-12-20T12:23:34)',
	s0d1b:          'Nombre de usuario de ACS:',
	s0d1c:          'Contraseña de ACS:',
	s0d1d:          '(de 1 a 256 caracteres)',
	s0d1e:          'Nombre de usuario de conexión:',
	s0d1f:          'Contraseña de usuario de conexión:',
	s0d20:          '(de 1 a 256 caracteres)',
	s0d21:          'Aplicar',
	s0d22:          'Cancelar',
	s0d23:          'Habilitar la autenticación de certificado y establecer una contraseña.',
	s0d24:          'Para permitir que el dispositivo se conecte al ACS en modo SSL, se puede habilitar la autenticación de certificados, establecer la contraseña de la clave privada e importar el certificado provisto por el operador.',
	s0d25:          'Habilitar autenticación de certificado:',
	s0d26:          'Contraseña de clave privada:',
	s0d27:          '(De 1 a 32 caracteres. Esta contraseña se implementará después de reiniciar).',
	s0d28:          'Confirmar contraseña:',
	s0d29:          'Importar certificado',
	s0d2a:          'Certificado:',
	s0d2b:          'Buscar',
	s0d2c:          'Importar certificado',
	s0d2d:          'La URL de ACS incluye un puerto no válido.',
	s0d2e:          'La URL ACS no contiene caracteres ASCII.',
	s0d2f:    "ACS URL:",
	s0d30:    "DSCP:",
	s0d31:    "Nivel de seguridad de contraseña de ACS muy bajo. ¿Confirma continuar?",
	s0d32:    "Nivel de seguridad de la contraseña de solicitud de conexión muy bajo. ¿Confirma continuar?",
	s0d33:    "Los niveles de seguridad de las contraseñas de ACS y de la solicitud de conexión son muy bajos. ¿Confirma continuar?",
	s0d34:"[1 - 2147483647](s)",
	s0d35:"(0~63)",
	s0d36:"Habilitar gestión de ACS:"
};
               
﻿var UsbstatusLgeDes =
{
	s0401:'Esta página permite ver el estado del dispositivo USB.',
	s0402:'Estado del USB:',
	s0403:'Desconectado',
	s0404:'Conectado',
	s0405:'Estado del USB'
};
 
﻿var UsbHostLgeDes =
{
	s1436:    "Directorio de búsqueda",
	s1439:    "El nivel de seguridad de la contraseña es bajo. ¿Continuar?",
	s1605:    "Examinar...",
	ss1116b:  "1. Se recomienda que la contraseña contenga al menos seis caracteres.<br/>2. Se recomienda incluir al menos dos de los siguientes tipos de caracteres en la contraseña: dígitos, letras en mayúscula y minúscula y caracteres especiales.Los caracteres especiales pueden ser los siguientes: `~!@#$%^&*()-_=+|[{}];:'&lt;,.&gt;/?<br/>3. Se recomienda que la contraseña no sea el nombre de usuario ni este al revés.",
	s0501:    'La ID del puerto no es válida.',
	s0502:    'La ID del puerto no es válida. Ingresar un número del 1 al 65535.',
	s0503:    'El nombre del usuario es demasiado largo. La longitud no puede superar los 255 caracteres.',
	s0504:    'Ingresar un nombre de usuario válido.',
	s0505:    'El nombre de usuario no debe contener espacios.',
	s0506:    'La contraseña es demasiado larga.',
	s0507:    'Contraseña no válida.',
	s0508:    'La ruta es demasiado larga.',
	s0509:    'Ruta no válida.',
	s050a:    'URL de FTP no válida.',
	s050b:    'La URL de FTP no debe contener espacios ni los siguientes caracteres: \n\< > \' \" { } [ ] % \\ ^ # |\"',
	s050c:    'Seleccionar un dispositivo USB.',
	s050d:    'El nombre de usuario es demasiado largo. La longitud no puede superar los 256 caracteres.',
	s050e:    'Ingresar el nombre de usuario.',
	s050f:    'Nombre de usuario no válido.',
	s0510:    'El nombre de usuario con espacios no es válido.',
	s0511:    'La contraseña es demasiado larga. La longitud no puede superar los 256 caracteres.',
	s0512:    'El campo de la contraseña no puede quedar vacío.',
	s0513:    'Contraseña no válida.',
	s0514:    'Primero seleccionar un dispositivo USB.',
	s0515:    'La ruta raíz es demasiado larga. La longitud no puede superar los 256 caracteres.',
	s0516:    'Ruta raíz no válida.',
	s0517:    'Si se cambia la configuración se reiniciará el servidor FTP. ¿Está seguro de continuar?',
	s0518:    'Configuración del cliente FTP',
	s0519:    'Esta página nos permite configurar el cliente FTP le permitira descargar archivos de servidor FTP al equipo de almacenamiento USB.',
	s051a:    'ID del puerto:',
	s051b:    'Nombre de usuario:',
	s051c:    'Contraseña:',
	s051d:    'Dispositivo USB:',
	s051e:    'Ruta:',
	s051f:    'Descargar',
	s0520:    'Estado',
	s0521:    'Configuración del servidor FTP',
	s0522:    'Esta página nos permite configurar el servidor FTP le permitirá compartir datos en un dispositivo de almacenamiento masivo USB en la LAN.',
	s0523:    'Habilitar el acceso del lado LAN/WAN al ONT vía el FTP y seleccionar el modo UTF-8.',
	s0524:    'Habilitar el servidor FTP:',
	s0525:    'Ruta raíz:',
	s0526:    'Aplicar',
	s0527:    'Cancelar',
	s0528:    'Nombre de usuario',
	s0529:    'Contraseña',
	s052a:    'ID del puerto',
	s052b:    'Ruta',
	s052c:    'La contraseña no puede comenzar con un espacio.',
	s052d:    'La contraseña no puede finalizar con un espacio.',
	s052e:    'No hay dispositivo USB',
	s052f:    "FTP URL:",
	s0530:    "FTP URL",
	s0531:    "Precaución:",
	s0532:    "No extraer y volver a insertar el dispositivo USB cuando está en uso, pueden dañarse los archivos almacenados.",
	s0533:    "Este archivo ya existe en el dispositivo USB. ¿Confirma reemplazarlo?",
	s0534:    "La dirección URL FTP no puede contener los siguientes caracteres: \"<, >, \', \", {, }, [, ], \\, ^, #, |\".",
	s0535:    '(/ejemplo: test/test.txt)',
	s0536:    "Esta página permite configurar el cliente FTP para la descarga de archivos en un dispositivo de almacenamiento del gateway residencial y configurar el servidor FTP para el uso compartido de recursos.",
	s0537:    "<strong class=\"color_red\">Al configurar el servidor FTP, habilite la función FTP del lado de la LAN o WAN y seleccione el código de caracteres en el formato UTF-8.</strong>",
	s0538:    "Configuración de FTP",
	s0539:    "Esta página permite configurar el cliente FTP para la descarga de archivos en un dispositivo de almacenamiento del gateway residencial y configurar el servidor FTP para el uso compartido de recursos.<br> Al configurar el servidor FTP, habilite la función FTP del lado de la LAN o WAN y seleccione el código de caracteres en el formato UTF-8.<br>Precaución:<br>No extraer y volver a insertar el dispositivo USB cuando está en uso, pueden dañarse los archivos almacenados.",
	s0540:	  "El dispositivo USB está en modo solo lectura, y no se pueden escribir datos.",
	s0541:	  "La tarjeta SD está en modo solo lectura, y no se pueden escribir datos.",
	s0542:	  "El dispositivo de almacenamiento está en modo solo lectura, y no se pueden escribir datos.",
	s0543:    "El puerto configurado está en conflicto con el puerto de servicios interno.",
	s0544:    "El puerto configurado está en conflicto con el puerto del servicio de mapeo de puertos.",
	s0545:    "El puerto configurado está en conflicto con el puerto del servicio de activación de puertos.",
	s0546:    "El puerto configurado está en conflicto con el puerto de servicios de voz.",
	s0547:    "El puerto configurado está en conflicto con el puerto de servicios FTP.",
	s0548:    "Extraer dispositivos USB",
	s0549:    "Esta página permite extraer dispositivos USB conectados.",
	s0550:    "Extraer dispositivos USB",
	s0551:    "Extraer",
	s0552:    "Actualizar",
	s0553:    "¿Confirma extraerlo?",
	s0554:    "El dispositivo USB seleccionado no está conectado o fue extraído.",
	s0555:    "Solo es posible identificar el dispositivo USB una vez que se extrae y se inserta.<br>Si se están realizando operaciones de lectura/escritura de datos en el dispositivo USB que se desea extraer, es posible que se pierdan datos."
};
 
﻿var LogviewLgeDes =
{
	s0100:    "Esta página permite configurar, descargar y consultar registros de usuario.",
	s0100a:   "Esta página permite descargar y consultar registros de usuario.",
	s0101:    "Registro de usuario",
	s1613:    "View Logs",
	s1614:    "You can view log information in the box below.",
	s0b01:    'Habilitar filtrado y configurar el nivel de filtrado',
	s0b02:    'Esta página permite especificar si se guardan los logs y si se configura el nivel de filtrado.',
	s0b03:    'Guardar Log:',
	s0b04:    'Nivel de filtro:',
	s0b05:    'Emergencia',
	s0b06:    'Alerta',
	s0b07:    'Crítico',
	s0b08:    'Error',
	s0b09:    'Precaución',
	s0b0a:    'Aviso',
	s0b0b:    'Informativo',
	s0b0c:    'Debug',
	s0b0d:    'Aplicar',
	s0b0e:    'Cancelar',
	s0b0f:    'Descargar o revisar el log',
	s0b10:    'En esta opción se podrá visualizar y descargar el Log.',
	s0b11:    'Descargar Archivo del log',
	s0b12:    "Activación de filtro",
	s0b13:    "Esta página permite activar y desactivar el filtro para realizar un respaldo del Log",
	s0b14:    "Tipo de log:",
	s0b15:    "Log de config",
	s0b16:    "Log de shell",
	s0b17:    "Log de alarma",
	s0b18:    "Todo tipo de logs"
};
 
